Most of the work done

diff --git a/start b/start
--- a/start
+++ b/start
@@ -80,10 +80,23 @@ check_parameters () {
 
 set_defaults_values () {
   project_name="intel_owl"
-  version=current_version
-  export PYELASTIC_VERSION=pyelastic_default_version
-  export PYCTI_VERSION=pycti_default_version
+  version=$current_version
+  export PYELASTIC_VERSION=$pyelastic_default_version
+  export PYCTI_VERSION=$pycti_default_version
 }
+
+load_env () {
+  export "$(grep -v '^#' $1 | xargs -d '\n')"
+}
+
+join_by_string() {
+  local separator="$1"
+  shift
+  local first="$1"
+  shift
+  printf "%s" "$first" "${@/#/$separator}"
+}
+
 # we should be able to start only with this script even the first time
 #  if ! [ -d venv/ ]; then
 #    ./initialize.sh
@@ -93,7 +106,7 @@ set_defaults_values () {
 
 check_parameters "$@" && shift 2
 
-export "$(grep -v '^#' docker/.env | xargs -d '\n')"
+load_env "docker/.env"
 current_version=${REACT_APP_INTELOWL_VERSION/"v"/""}
 pyelastic_default_version="7.4.1"
 pycti_default_version="5.10.0"
@@ -104,17 +117,20 @@ declare -A path_mapping=(["default"]="docker/default.yml" ["postgres"]="docker/p
 for value in "${docker_analyzers[@]}"; do
   path_mapping["${value}"]+="integrations/${value}/compose.yml"
   path_mapping["${value}.test"]+="integrations/${value}/compose-tests.yml"
-  path_mapping["all_analyzers"]+="${path_mapping[${value}]} ";
-  path_mapping["all_analyzers.test"]+="${path_mapping["${value}.test"]} ";
+  # cannot use a list as value of associative array. we have to use a string and convert dynamically
+  path_mapping["all_analyzers"]+="${path_mapping[${value}]} "
+  path_mapping["all_analyzers.test"]+="${path_mapping["${value}.test"]} "
 done
 
 test_appendix=""
 if ! [[ ${test_mode["${env_argument}"]} ]]; then
   is_test=true
-  test_appendix="test"
+  test_appendix=".test"
 fi
 
-# parse arguments
+# parse arguments and put them in an associative array to better use them later
+declare -A params
+declare -A analyzers
 set_defaults_values
 while [[ $# -gt 0 ]]; do
   case $1 in
@@ -131,31 +147,47 @@ while [[ $# -gt 0 ]]; do
     shift 2
   ;;
   --all_analyzers)
-    all_analyzers=true
+    analyzers["all_analyzers"]=true
     shift 1
   ;;
+  --tor_analyzers)
+    analyzers["tor_analyzers"]=true
+    shift 1
+    ;;
+  --malware_tools_analyzers)
+    analyzers["malware_tools_analyzers"]=true
+    shift 1
+    ;;
+  --cyberchef)
+    analyzers["cyberchef"]=true
+    shift 1
+    ;;
+  --pcap_analyzers)
+    params["pcap_analyzers"]=true
+    shift 1
+    ;;
   --multi_queue)
-    multi_queue=true
+    params["multi_queue"]=true
     shift 1
   ;;
   --nfs)
-    nfs=true
+    params["nfs"]=true
     shift 1
   ;;
   --use-external-database)
-    use_external_database=true
+    params["use_external_database"]=true
     shift 1
   ;;
   --use-external-broker)
-    use_external_broker=true
+    params["use_external_broker"]=true
     shift 1
   ;;
   --flower)
-    flower=true
+    params["flower"]=true
     shift 1
   ;;
   --custom)
-    custom=true
+    params["custom"]=true
     shift 1
   ;;
   --debug-build)
@@ -163,7 +195,7 @@ while [[ $# -gt 0 ]]; do
     shift 1
   ;;
   --elastic)
-    elastic=true
+    params["elastic"]=true
     shift 1
   ;;
   --pyelastic-version)
@@ -183,14 +215,14 @@ while [[ $# -gt 0 ]]; do
     shift 2
   ;;
   --https)
-    https=true
+    params["https"]=true
     shift 1
   ;;
   -h | --help)
     print_help
     exit 0
     ;;
-  --) shift; break;; # explicit end of arguments
+  --) shift 1; break;; # explicit end of arguments
   *)
     echo "Error! Invalid option $1."
     exit 1
@@ -201,10 +233,91 @@ done
 # here all variables should be parsed and ready for use
 cmd_py_version=("up" "build")
 if [[ ( ! $env_argument == "test" || ${cmd_py_version[*]} =~ $cmd_argument ) && \
-  ( $PYELASTIC_VERSION != pyelastic_default_version || \
-  $PYCTI_VERSION != pycti_default_version ) ]]; then
+  ( $PYELASTIC_VERSION != $pyelastic_default_version || \
+  $PYCTI_VERSION != $pycti_default_version ) ]]; then
     echo "pycti_version and pyelastic_version options are valid only while running in" >&2
     echo "'test' mode and while building a new image. This is because they can change" >&2
     echo "the version of those library only during the build of a new Docker Image." >&2
     exit 11
 fi
+
+# load relevant .env file
+load_env "docker/.env.start${test_appendix}"
+
+# check if all_analyzers and other flags have been used
+for value in "${docker_analyzers[@]}"; do
+  if [ "${params[$value]}" ]; then
+    docker_flags+=("${value}")
+  fi
+done
+if [ "$all_analyzers" ] && ! [ ${#docker_flags[@]} -eq 0 ]; then
+  echo "It is not possible to select both --all_analyzers and another docker container."
+  exit 1
+fi
+
+# default file
+compose_files=("${path_mapping["default"]}")
+if ! [ "${params["use_external_database"]}" ]; then
+  compose_files+=("${path_mapping["postgres"]}")
+fi
+if ! [ "${params["use_external_broker"]}" ]; then
+  compose_files+=("${path_mapping["rabbitmq"]}")
+fi
+if $is_test; then
+  compose_files+=("${path_mapping["$env_argument"]}")
+fi
+
+# add all the other ones
+for value in "${!params[@]}"; do
+  if [ "${params[$value]}" ]; then
+    compose_files+=("${path_mapping["$value"]}")
+  fi
+done
+# add all the test files
+if [[ $env_argument == "test" ]]; then
+  test_values=("multi_queue" "flower")
+  for value in "${test_values[@]}"; do
+    if [ "${params[$value]}" ]; then
+      compose_files+=("${path_mapping["test_$value"]}")
+    fi
+  done
+fi
+
+# add and parse analyzers
+if [ "${analyzers["all_analyzers"]}" ]; then
+  IFS=', ' read -r -a all_analyzers_array <<< "${path_mapping["all_analyzers"]}"
+  for analyzer in "${all_analyzers_array[@]}" ; do
+    compose_files+=("${path_mapping["$analyzer"]}")
+  done
+  if [ $is_test ]; then
+    IFS=', ' read -r -a all_analyzers_array_test <<< "${path_mapping["all_analyzers${test_appendix}"]}"
+    for analyzer in "${all_analyzers_array_test[@]}" ; do
+      compose_files+=("${path_mapping["$analyzer"]}")
+    done
+  fi
+fi
+
+if [[ $env_argument == "prod" && $version -ne $current_version ]]; then
+  echo "Requested version ${version} is different from current version ${current_version}"
+  git config --global --add safe.directory "$(pwd)" # it could be not the right directory, to verify during tests
+  git checkout tags/"$current_version"
+fi
+
+# build final command
+docker compose version > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "Error! Docker compose V2 not installed." >&2
+  exit 127
+fi
+
+if [ $debug_build ]; then
+  export BUILDKIT_PROGRESS="plain"
+fi
+export DOCKER_BUILDKIT=1
+
+for value in "${compose_files[@]}" ; do
+  to_run+=" -f $value"
+done
+echo sudo docker compose -p "$project_name" --project-directory docker"${to_run[*]}" "$cmd_argument" "$@"
+sudo docker compose -p "$project_name" --project-directory docker"${to_run[*]}" "$cmd_argument" "$@"
+# TODO: intercept CTRL+C
