Improved error message

diff --git a/start b/start
--- a/start
+++ b/start
@@ -298,7 +298,7 @@ fi
 # build final command
 docker compose version > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-  echo "Error! Docker compose V2 not installed." >&2
+  echo "Error! Docker compose V2 not installed. Run ./initialize.sh to check for all dependencies." >&2
   exit 127
 fi
 
